version: '3'

services:
  sbiport-db:
    image: mariadb:10.7.3
    restart: always
    container_name: sbiport-db
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sbiport
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    volumes:
      - ./migration/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  sbiport-server:
    image: sbiport-server:latest
    container_name: sbiport-server
    ports:
      - "8080:80"
    environment:
      - MYSQL_DATABASE=sbiport
    command:
      - "--db-host"
      - "sbiport-db"
